### ISSUE TITLE
Migrating from Windows SBS 11 to Windows server 2016 - error in Active Directory

### ISSUE THREAD

**Issue by srikanth1997-in** [dsccommunity/dsccommunity.org#148]
Hi, I m trying to migrate the Windows SBS 11 to Windows server 2016 while in migration process, i am trying to install "Install-ADDSDomainController " in Power Shell, but I am Getting the below error....

Install-ADDSDomainController : Verification of prerequisites for Domain Controller promotion failed. The specified argument 'ConfirmGC' was not recognized.
At line:1 char:1
+ Install-ADDSDomainController -NoGlobalCatalog:$false -CreateDnsDelega ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-ADDSDomainController], TestFailedException
    + FullyQualifiedErrorId : Test.VerifyDcPromoCore.DCPromo.General.77,Microsoft.DirectoryServices.Deployment.PowerShell.Commands.InstallADDSDomainControllerCommand

Message                                                                                                                        Context                                   RebootRequired Status
-------                                                                                                                        -------                                   -------------- ------
Verification of prerequisites for Domain Controller promotion failed. The specified argument 'ConfirmGC' was not recognized... Test.VerifyDcPromoCore.DCPromo.General.77          False  Error

Please suggest the solution for the above..............

**Comment by PlagueHO** [comment]
Hi @srikanth1997-in - can you re-post this issue over in the ActiveDirectoryDsc resource module repo? https://github.com/dsccommunity/ActiveDirectoryDsc/issues

This repo just covers the dsccommunity.org web site :grin:
