### ISSUE TITLE
Add required version of Hugo to the README.md

### ISSUE THREAD

**Issue by johlju** [dsccommunity/dsccommunity.org#15]
And/or link to the theme https://themes.gohugo.io/dot-hugo-documentation-theme/ that shows the required version, though we might  not have the latest at all times. So good for users to know the minimum version needed.

**Comment by johlju** [comment]
GitHub repo for the theme we use https://github.com/themefisher/dot-hugo-documentation-theme

**Comment by gaelcolas** [comment]
Yeah, as I'm modifying it every now and then, maybe we should rename that theme at some points as it'll become more and more custom over time...

**Comment by johlju** [comment]
Yeah, it might be good if we customizing it.
