### ISSUE TITLE
Split rows in markdown around ~80 characters

### ISSUE THREAD

**Issue by johlju** [dsccommunity/dsccommunity.org#19]
I suggest that we in markdown files split lines around ~80 characters were applicable. Then it will be easier to make review comments and the contributor to see where the requested changes are (without scrolling). It is also easier to see the lines in split view mode when the lines don't wrap.

In VS Code there is a tool that can help with this when writing markdown. It is possible to add a ruler for just markdown in a workspace settings.json file in this repo.

```json
{
    "[markdown]": {
        "editor.rulers": [
            80
        ]
    }
}
```

**Comment by gaelcolas** [comment]
80 sounds good to me. Any reason it should be shorter?

**Comment by johlju** [comment]
80 works. I think I used 72 when I had a lower resolution monitor, and the split-view was smaller. Not an issue anymore. 🙂

**Comment by johlju** [comment]
We should also update http://localhost:1313/guidelines/markdown-files/

> If a paragraph includes more than one sentence, end each sentence with a newline. GitHub will still render the sentences as a single paragraph, but the readability of git diff will be greatly improved.
