### ISSUE TITLE
HRESULT 0x80041033 on Start-DscConfiguration or Update-DscConfiguration

### ISSUE THREAD

**Issue by gbrissard** [dsccommunity/dsccommunity.org#198]
Hi,

Got an issue for the past couple weeks, on Windows Server 2019 and 2022 (2016 is somehow not impacted). Any time I try to start or update the DSC configuration, this happens :

![image](https://user-images.githubusercontent.com/45941243/181033382-f1bbe3ac-492b-4a86-93e9-85cc3b8baf5a.png)

I am using partial configurations.

I've tried the following :

- Anything I could find on internet regarding WMI 0x80041033 in general
- Checking every conf I have for errors/duplicates
- Repackaged all my resources
- I even removed last installed updates without any success

I am now super stuck, I really hope someone in the community can help me !

**Comment by PlagueHO** [comment]
Hi @gbrissard - the best place to get help on this would be over in the #dsc channel in the PowerShell Slack. You can find detail on how to get to that here https://dsccommunity.org/community/contact/

**Comment by gbrissard** [comment]
I'll go there then, thank you !

**Comment by johlju** [comment]
Closing this issue since this will most likely not get answered here as per previous comment.
