### ISSUE TITLE
Add Reviewable as a review tool for pull requests

### ISSUE THREAD

**Issue by johlju** [dsccommunity/dsccommunity.org#25]
Using GitHub's internal review tool has it limitations. I suggest we add Reviewable which is a more powerful review tool (and it is free for public open source projects).

/cc @PlagueHO @gaelcolas

**Comment by gaelcolas** [comment]
Just Do it ;)

**Comment by johlju** [comment]
Reviewable is enabled on the organization so all future repos is enabled for it too.

/cc @PlagueHO
