### ISSUE TITLE
List style issue in blog posts

### ISSUE THREAD

**Issue by ykuijs** [dsccommunity/dsccommunity.org#63]
While verifying the markup of a blog post I am creating using Hugo I ran into some issues with ordered and unordered lists, which are not displayed properly:
 
![dsccommunity](https://user-images.githubusercontent.com/15103891/66138665-4a734400-e5ff-11e9-8627-5c223c6ecf28.jpg)

I have been able to validate that the marked CSS style marked as well in the above screenshot is the culprit. If I disable this style, the lists are displayed fine.

**Comment by gaelcolas** [comment]
I'm happy in principle, just need to make sure this change does not affect other parts of the site in. Bad way.
Will look when on PC.

**Comment by gaelcolas** [comment]
This should be fixed, let me know if you have any issue.
