### ISSUE TITLE
Add a page/list for Community Calls & agenda

### ISSUE THREAD

**Issue by gaelcolas** [dsccommunity/dsccommunity.org#7]
We'll soon move the Community Calls & agenda to this new repository, so it would make sense to have a web page linking to the latest/next calls, and publish them & notes to the website (similar to how Joey does for PS in GH).

Do we need a section for it, or should it just go under Community? (would that scale)

**Comment by johlju** [comment]
Should we keep an archive of old calls and agendas, then a new section would be needed. But might be enough to have it in the top header. 🤔 
The 'Contact' the the top header does not provide any value as the "Join the conversation" link is at the end of the page. Switch that out to "Community Calls" that has pages similar to 'Community', though, that might make it end up as a block on the main page. It would be good if we could avoid that to keep the symmetry of the main page. 🤔

**Comment by gaelcolas** [comment]
As @PlagueHO mentioned offline, it'd be great to have a way to keep track of news/what have changed. That might also be summarised in the community calls.
New section might be just fine.

Regarding the Contact link in Navigation, I've replaced that with a help, with the different links with where to find help (docs, forums, slack/discord and so on...) in an upcoming PR ;)
