### ISSUE TITLE
content/blog/how-to-use-dsc-logging.en.md

### ISSUE THREAD

**Issue by randombuffalo** [dsccommunity/dsccommunity.org#71]
The method described in the section "Reading the active log file" doesn't work.  You don't have a comment section on the blog so I am writing a Github issue 😄 

Thanks for the great info!

**Comment by gaelcolas** [comment]
That's the right place for issues! Pinging @ykuijs the author.

**Comment by ykuijs** [comment]
Hi @randombuffalo, what exactly doesn't work? Do you get any error messages?

**Comment by randombuffalo** [comment]
Yeah I get an error that it is still in use, similar to other methods like Get-Content.

``` 
[kuiperDSCtest.mshome.net]: PS C:\Users\Administrator\Documents> [System.IO.FileStream]$fileStream = [System.IO.File]::Open('C:\Windows\System32\Configuration\ConfigurationStatus\{5C5CF6EB-FCB5-11E9-B
304-00155D000B0E}-0.details.json', [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
Exception calling "Open" with "4" argument(s): "The process cannot access the file 'C:\Windows\System32\Configuration\ConfigurationStatus\{5C5CF6EB-FCB5-11E9-B304-00155D000B0E}-0.details.json'
because it is being used by another process."
At line:1 char:1
+ [System.IO.FileStream]$fileStream = [System.IO.File]::Open('C:\Window ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IOException

**Comment by ykuijs** [comment]
Are you using the [script](https://raw.githubusercontent.com/ykuijs/Powershell/master/Dsc/DSCLogParser.ps1) mentioned at the bottom of the article??

**Comment by randombuffalo** [comment]
Oh no, I'm not.  I read that as a separate section entirely instead of a subsection.  That script might work but I am working with Server Core that doesn't support out-gridview.

Probably safe to close the issue under: "User Error" :)

**Comment by ykuijs** [comment]
I realize that the article isn't 100% clear. The article I was referring to contained the usable code a little further down: The Shadows Copy part.

If you run the script when the LCM is busy, the script opens the active log file right away without an Out-Gridview :-)

**Comment by randombuffalo** [comment]
Oh interesting, my LCM is busy but the shell still threw an error about Out-Gridview.
```
PS C:\Users\Administrator> & C:\dsclogparser.ps1
Out-GridView : To use the Out-GridView, install Windows PowerShell ISE by using Server Manager, and then restart this
application. (Could not load file or assembly 'Microsoft.PowerShell.GraphicalHost, Version=3.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.)
At C:\dsclogparser.ps1:17 char:210
+ ... Resources | Out-GridView -PassThru -Title "Please select the job you  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...1bf3856ad364e35:AssemblyName) [Out-GridView], NotSupp
   ortedException
    + FullyQualifiedErrorId : ErrorLoadingAssembly,Microsoft.PowerShell.Commands.OutGridViewCommand
```
When I replaced all the Out-Gridview with Format-Table I got the following output and saw the .JSON log!
```
PS C:\Users\Administrator> & C:\dsclogparser.ps1
Cannot read log files while the LCM is working. Opening the most recent log using ShadowCopy!
NOTE: Since the LCM only flushes log entries periodically, this log might not be 100% complete/accurate!
```

**Comment by ykuijs** [comment]
Ok, apparently Server Core checks the script for Out-Gridview even on lines it never touches.

Good to hear that your solutions worked!

**Comment by randombuffalo** [comment]
Thanks for the help and information!
